#!/usr/bin/env python3
"""Coverage linter: every contract signal must be exercised by some test.

SCHEMATIC IN, TESTS OUT. The signal list comes from the schematic (via
dino_sheet_contracts.md, itself generated by kicad_contracts.py), and the
evidence comes from the FPGA testbenches. Nothing in the middle is typed by
hand, including the module -> sheet-file mapping, which is read off each
component's own Sheetname/Sheetfile properties in the netlist.

WHY THIS CHANGED (2026-08-11). This linter used to grep the RIG FIRMWARE --
tests/dino_bringup/src/mod_<name>.c -- for each signal name. That made it a
rig-firmware completeness check and nothing else, and when the Mega was
detached it started reporting gaps nobody could close: not wrong, just
measuring a frozen dimension. The FPGA is the primary instrument now, so the
gate moved to where the tests actually run.

TWO TIERS, and the distinction is the point:

    MODULE   the signal appears in fpga/sim/test_module_<sheet>.py --
             unit-tested at its own boundary, which is where a failure names
             the module directly.
    CORE     it appears only in a whole-core test (test_core_*.py) or a TTL
             model test -- exercised, but black-box: a failure tells you the
             machine is wrong, not which sheet.

Both count as covered. The report separates them so the map stays honest:
when the bench comes back and something is broken, a CORE-only signal is one
you have no unit-level evidence for and should look at first.

Exit 0 = every contract signal is exercised somewhere. Modules with no
testbench at all are listed as pending and do not fail the run.

Run: python3 coverage_lint.py [--verbose]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
CONTRACTS = os.path.join(HERE, "dino_sheet_contracts.md")
ROOT_SCH = os.path.join(REPO, "dino_v0_0_2", "dino_v0_0_2.kicad_sch")
SIM = os.path.join(REPO, "fpga", "sim")
TTL = os.path.join(REPO, "fpga", "ttl")

sys.path.insert(0, HERE)
import fpga_gen as fg                      # noqa: E402  (sanitizer + netlist)


def expand(label):
    """"CW0-8" -> CW0..CW8. Alias names are kept WHOLE.

    A dual-labelled net's port is named after BOTH halves --
    "CW17=~{SRC_BANK}" becomes `cw17_eq_n_src_bank`, not `n_src_bank` -- so
    splitting on "=" and keeping one half finds nothing. Kept whole here and
    both halves offered as fallbacks in _idents(), because which spelling a
    testbench reaches for depends on whether the sheet consumes the CW bit or
    the aliased signal.
    """
    m = re.match(r"^(.*?)(\d+)-(\d+)$", label)
    if not m:
        return [label]
    return [f"{m.group(1)}{i}" for i in range(int(m.group(2)), int(m.group(3)) + 1)]


def sheet_files():
    """Sheetname -> sheet-file stem, read straight off the netlist.

    Every component carries both properties, so "Memory Address Regiser" ->
    "mar" and "Output" -> "input_output" are FACTS from the schematic rather
    than a hand-kept table that can drift when a sheet is renamed. The old
    version of this file had exactly such a table, and it mapped "Output" to
    "io" (the rig firmware's name) -- which would have pointed at the wrong
    testbench the moment this linter started reading fpga/sim/.
    """
    txt = open(fg.kxa.export_netlist(ROOT_SCH)).read()
    out = {}
    for block in txt.split("(comp\n")[1:]:
        name = re.search(r'\(name "Sheetname"\)\s*\(value "([^"]*)"\)', block)
        fileprop = re.search(r'\(name "Sheetfile"\)\s*\(value "([^"]+)"\)', block)
        if name and fileprop:
            stem = fileprop.group(1).rsplit(".", 1)[0]
            out[name.group(1).strip()] = "root" if stem.startswith("dino_v0_0") else stem
    return out


def parse_contracts(name_to_sheet):
    mods, cur = {}, None
    for line in open(CONTRACTS):
        h = re.match(r"^## (.+)$", line)
        if h:
            title = h.group(1).strip()
            cur = name_to_sheet.get(title, title.lower().replace(" ", "_"))
            mods.setdefault(cur, set())
            continue
        m = re.match(r"^- (IN|OUT|BIDIR)\s+(.+?)\s+(?:<->|<-|->)", line)
        if m and cur:
            for part in m.group(2).split(", "):
                mods[cur].update(expand(part.strip()))
    return mods


def _read(path):
    return open(path).read() if os.path.exists(path) else ""


def _idents(sig):
    """Every identifier a testbench could plausibly use for this signal.

    A bus MEMBER is covered by the bus. fpga_gen emits `MDR0-7` as ONE vector
    port `mdr` (or the `mdr_i`/`mdr_o` split pair when the sheet both drives
    and reads it), so a testbench writes `dut.mdr.value` and the string
    "mdr3" appears nowhere. Matching only the per-bit name reported 100+
    false gaps on the first run of this rewrite -- every data and address bus
    in the machine.

    So: the sanitized name itself, plus, for a trailing-digit name, the bus
    base and its _i/_o split forms.
    """
    forms = {sig}
    if "=" in sig:                       # dual-labelled net: either half works
        forms |= set(sig.split("="))
    out = set()
    for f in forms:
        out.add(f)
        ident = fg._sanitize_name(f)
        if not ident:
            continue
        out.add(ident)
        m = re.match(r"^(.*?)(\d+)$", ident)
        if m and m.group(1):
            base = m.group(1)
            out |= {base, f"{base}_i", f"{base}_o"}
    return {o for o in out if o}


def _found(sig, text):
    if not text:
        return False
    return any(re.search(rf"\b{re.escape(o)}\b", text) for o in _idents(sig))


def main(argv):
    verbose = "--verbose" in argv
    name_to_sheet = sheet_files()
    mods = parse_contracts(name_to_sheet)

    # Whole-core + TTL-model evidence, read once. A signal found only here is
    # exercised black-box: the machine proves it, no sheet-level test names it.
    core_text = "".join(
        _read(os.path.join(SIM, f)) for f in sorted(os.listdir(SIM))
        if f.startswith("test_core_") and f.endswith(".py"))
    core_text += "".join(
        _read(os.path.join(TTL, f)) for f in sorted(os.listdir(TTL))
        if f.startswith("test_") and f.endswith(".py"))
    # The whole-core HARNESS is test code too: the reset sequencer, the
    # standing invariant monitor and run_program() all live here, and several
    # signals are only ever named there (dino_core-internal nets with no
    # port, like ~{RESET}).
    core_text += _read(os.path.join(SIM, "conftest_helpers.py"))

    failures, pending, core_only = [], [], []
    for mod, signals in sorted(mods.items()):
        if not signals:
            continue
        unit = _read(os.path.join(SIM, f"test_module_{mod}.py"))
        if not unit and mod != "root":
            pending.append(mod)
        missing, only_core = [], []
        for sig in sorted(signals):
            if _found(sig, unit):
                continue
            if _found(sig, core_text):
                only_core.append(sig)
                continue
            missing.append(sig)
        if missing:
            failures.append((mod, missing))
        if only_core:
            core_only.append((mod, only_core))

    for mod, missing in failures:
        print(f"UNCOVERED {mod}: {', '.join(missing)}")
    for mod, sigs in core_only:
        detail = f": {', '.join(sigs)}" if verbose else f" ({len(sigs)} signals)"
        print(f"core-only {mod}{detail}")
    for mod in pending:
        print(f"no module testbench: {mod}")

    n_core = sum(len(s) for _, s in core_only)
    print(f"{len(failures)} module(s) uncovered, {n_core} signal(s) core-only, "
          f"{len(pending)} module(s) without a testbench")
    if not verbose and core_only:
        print("  (--verbose names the core-only signals)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
