#!/usr/bin/env python3
"""Host test for kicad_contracts.py --pinmap. Run: python3 test_kicad_contracts_pinmap.py"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "tests", "dino_bringup", "src", "pinmap_gen.h")

subprocess.run([sys.executable, os.path.join(HERE, "kicad_contracts.py"), "--pinmap"],
               check=True, capture_output=True)
t = open(OUT).read()

assert t.splitlines()[0].startswith("/* GENERATED by kicad_contracts.py"), "missing generated marker"

# Tables must live in flash: interned PROGMEM strings + PROGMEM struct arrays.
assert "#include <avr/pgmspace.h>" in t, "missing pgmspace include"
strings = dict(re.findall(r'static const char (pm_s\d+)\[\] PROGMEM = "([^"]*)";', t))
assert strings, "no interned PROGMEM strings emitted"

# Resolve each sig_<mod> block back to (signal, pin, dir) tuples.
modules = {}  # tok -> [(sig, pin, dir), ...]
for tok, block in re.findall(r'static const sigpin_t sig_(\w+)\[\] PROGMEM = \{(.*?)\};', t, re.S):
    rows = re.findall(r"\{(pm_s\d+), (pm_s\d+), '(\w)'\}", block)
    assert rows, f"sig_{tok} has no parseable rows"
    modules[tok] = [(strings[s], strings[p], d) for s, p, d in rows]
assert modules, "no sig_<mod> PROGMEM blocks found"

# MODMAPS must be PROGMEM and reference the module name strings + arrays.
mm = re.search(r'static const modmap_t MODMAPS\[\] PROGMEM = \{(.*?)\};', t, re.S)
assert mm, "MODMAPS must be PROGMEM"
mod_names = [strings[s] for s, _tok, _n in
             re.findall(r'\{(pm_s\d+), sig_(\w+), (\d+)\}', mm.group(1))]
for s, tok, n in re.findall(r'\{(pm_s\d+), sig_(\w+), (\d+)\}', mm.group(1)):
    assert strings[s] == tok, f"MODMAPS name {strings[s]} != array token {tok}"
    assert int(n) == len(modules[tok]), f"MODMAPS count mismatch for {tok}"

# The bus-position rules below are POOL-ALLOCATION invariants: they hold
# for modules whose pins the generator hands out. They do NOT hold for
# modules pinned BY THE BENCH, and those outrank the generator by
# definition:
#
#   alu     Rico, 2026-07-26: "Change the code for the ALU only on the test
#           rig. It's assigned arbitrarily. full stop. MEGA SHOULD BEND TO
#           THE DUT." The strip's slot map is AS-BUILT and FROZEN
#           (layout_gen.py); PIN_ASSIGN follows it with pin = slot + 17.
#   memory  ribbon-first bench call: both byte buses in one unbroken 24-pin
#           run, D53->D30 (MDR0-7 = D53-D46, M0-M15 = D45-D30).
#
# Read the exempt set straight from PIN_ASSIGN so this stays true when the
# bench pins another module by hand — same discipline as everything else
# here: derive it, don't retype it.
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location(
    "kicad_contracts", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "kicad_contracts.py"))
_kc = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_kc)
PIN_ASSIGN = getattr(_kc, "PIN_ASSIGN", {})
assert PIN_ASSIGN, "PIN_ASSIGN empty — exemption set would silently vanish"

# Exempt PER SIGNAL, not per module: a hand-pinned module can still have
# pool-allocated signals, and those must keep obeying the bus rules.
for tok, rows in modules.items():
    bench_pinned = PIN_ASSIGN.get(tok, {})
    for sig, pin, _d in rows:
        if sig in bench_pinned:
            continue
        # W bus pinned to PORTA in every module that has it
        if sig == "W0":
            assert pin.startswith("PA0"), f"W0 must be PA0/D22, got {pin} in {tok}"
        # MDR bus on PORTF
        if sig == "MDR0":
            assert pin.startswith("PF0"), f"MDR0 must be PF0/A0, got {pin} in {tok}"
        # alias-joined bus bits still land on their bus port (Task 3 reads whole ports)
        if "M15" in sig:
            assert pin.startswith("PL7"), f"{sig} must be PL7/D42, got {pin} in {tok}"
        if "SA2" in sig:
            assert pin.startswith("PL1/D48"), f"{sig} (=CW9) must be PL1/D48, got {pin} in {tok}"
assert any("M15" in sig for rows in modules.values() for sig, _p, _d in rows), \
    "no M15 signal mapped"

# every module block present (sheet names, lowercased tokens)
for mod in ("root", "mar", "memory", "control_word"):
    assert mod in mod_names, f"module {mod} missing"

# no signal assigned two different pins within one module
for tok, rows in modules.items():
    seen = {}
    for sig, pin, _d in rows:
        assert sig not in seen, f"duplicate signal {sig} in {tok}"
        seen[sig] = pin
    assert len(set(seen.values())) == len(seen), f"pin double-booked in {tok}"
print("pinmap host test: OK")
