import cocotb
from cocotb.clock import Clock
from cocotb.triggers import Timer
from cocotb.types import Logic

# Memory-model testbenches (Task 6): AT28C64B (8K microcode EEPROM),
# AT28C256 (32K program EEPROM) -- Task-13 rework item 2 gave both a
# clk_sys-REGISTERED read (same hidden-sampling-clock contract every
# stateful model uses, so memory_libmap can map them to DP16KD blocks
# instead of falling back to flip-flops; they joined CLK_SYS_TYPES, not
# STATEFUL_TYPES itself -- see docs/notes/fpga_gen.py's comment) -- and
# MCM60256AP (32K SRAM) -- the original STATEFUL_TYPES member here, WE_n
# sampled through clk_sys (see ttl_mcm60256.vhd's header for the full
# derivation), which ALSO gained a registered read this task and had its
# dq0-7 pins split from `inout` into `_i`/`_o` pairs (item 1: ghdl-yosys-
# plugin severs internal nets touching a sub-instance `inout` port at
# synthesis import). The Makefile's MODEL=ttl_at28c64b/ttl_at28c256/
# ttl_mcm60256 branches build against a small addr_bits=4 fixture
# (test_memory_16.hex, generated by docs/notes/fpga_gen.py's bin2hex()
# from these exact 16 bytes -- dogfooding the same function this task
# adds, not a hand-typed hex file), so every test here addresses exactly
# 16 locations regardless of the real chip's full depth.
#
# KNOWN_BYTES is deliberately NOT a monotonic run: each entry isolates a
# different bit (or a distinctive nibble pattern) so an address-line swap
# or a stuck/shorted data bit shows up as a wrong VALUE at a specific
# address, not just "off by one row".
KNOWN_BYTES = [0x00, 0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40,
               0x80, 0xFF, 0xAA, 0x55, 0x0F, 0xF0, 0x3C, 0xC3]

ADDR_BITS = 4  # matches test_memory_16.hex's 16 lines (2**4)

# Full physical address-pin lists, LSB first -- AT28C64B has 13 real
# address pins (a0..a12), AT28C256/MCM60256AP have 15 (a0..a14, the two
# extra over the '64B are NC on that part -- see PIN_MAP["AT28C64B"]'s
# comment in docs/notes/fpga_gen.py). Only the low ADDR_BITS pins carry a
# meaningful value in these tests; the rest are tied to '0' for hygiene
# (CLAUDE.md: unused inputs tied off, not left floating).
ADDR_PINS_13 = ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8",
                "a9", "a10", "a11", "a12"]
ADDR_PINS_15 = ADDR_PINS_13 + ["a13", "a14"]

SETTLE = 50   # ns -- >3 clk_sys cycles (10ns period), clears the RAM's
              # WE_n 2-flop sync -- same constant/rationale as Task 5's
              # stateful models (fpga/ttl/test_stateful.py).
HOLD = 250    # ns -- machine-realistic "clock"/strobe half-period.


def _drive_addr(dut, pin_names, addr):
    for i, name in enumerate(pin_names):
        bit = (addr >> i) & 1 if i < ADDR_BITS else 0
        getattr(dut, name).value = bit


def _read_bus(dut, prefix, n=8, suffix=""):
    v = 0
    for i in range(n):
        v |= (int(getattr(dut, f"{prefix}{i}{suffix}").value) & 1) << i
    return v


def _read_bus_str(dut, prefix, n=8, suffix=""):
    return [str(getattr(dut, f"{prefix}{i}{suffix}").value) for i in range(n)]


def _drive_bus(dut, prefix, val, n=8, suffix=""):
    for i in range(n):
        getattr(dut, f"{prefix}{i}{suffix}").value = (val >> i) & 1


def _release_bus(dut, prefix, n=8, suffix=""):
    for i in range(n):
        getattr(dut, f"{prefix}{i}{suffix}").value = Logic("Z")


# ROM reads are now REGISTERED on clk_sys (Task-13 rework item 2) -- a
# clock has to actually be running for `q` to ever leave its t=0 'U' init,
# and every address change needs at least one full clk_sys period to reach
# the register before the combinational tri-state gate can show it. 25ns
# (>2 clk_sys cycles at the 10ns period used everywhere else in this repo)
# is comfortable margin, same shape as Task 5's stateful-model settle time.
ROM_SETTLE = 25   # ns


async def _rom_exact_readback_and_deselect(dut, addr_pins, data_prefix):
    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    dut.ce_n.value = 1
    dut.oe_n.value = 1
    dut.we_n.value = 1
    _drive_addr(dut, addr_pins, 0)
    await Timer(ROM_SETTLE, unit="ns")

    # Deselected (CE_n=1): output must already be Z before any read.
    for v in _read_bus_str(dut, data_prefix):
        assert v == "Z", f"{data_prefix}: CE_n=1 at reset -> {v}, want Z"

    # Exact readback of every one of the 16 known bytes, address by
    # address -- this is the mirror-witness-adjacent check for ROM (no
    # write path exists to permute against, so exhaustive address-by-
    # address readback is the strongest available check).
    dut.ce_n.value = 0
    dut.oe_n.value = 0
    for addr, want in enumerate(KNOWN_BYTES):
        _drive_addr(dut, addr_pins, addr)
        await Timer(ROM_SETTLE, unit="ns")
        got = _read_bus(dut, data_prefix)
        assert got == want, f"addr={addr}: {data_prefix}=0x{got:02x}, want 0x{want:02x}"

    # CE_n high tristates regardless of OE_n.
    dut.ce_n.value = 1
    await Timer(ROM_SETTLE, unit="ns")
    for v in _read_bus_str(dut, data_prefix):
        assert v == "Z", f"{data_prefix}: CE_n=1 (deselect) -> {v}, want Z"

    # OE_n high alone (CE_n still selected) also tristates.
    dut.ce_n.value = 0
    dut.oe_n.value = 1
    await Timer(ROM_SETTLE, unit="ns")
    for v in _read_bus_str(dut, data_prefix):
        assert v == "Z", f"{data_prefix}: OE_n=1 (CE_n=0) -> {v}, want Z"


# --- AT28C64B: 8K microcode EEPROM (async read only) -----------------------

@cocotb.test()
async def rom64_exact_readback_and_deselect(dut):
    await _rom_exact_readback_and_deselect(dut, ADDR_PINS_13, "io")


# --- AT28C256: 32K program EEPROM (async read only) -------------------------

@cocotb.test()
async def rom256_exact_readback_and_deselect(dut):
    await _rom_exact_readback_and_deselect(dut, ADDR_PINS_15, "io")


# --- MCM60256AP: 32K SRAM, write-then-read + permuted-order witness --------

@cocotb.test()
async def ram_write_then_read_permuted(dut):
    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    await Timer(SETTLE, unit="ns")

    dut.ce_n.value = 1
    dut.oe_n.value = 1
    dut.we_n.value = 1
    _drive_addr(dut, ADDR_PINS_15, 0)
    _release_bus(dut, "dq", suffix="_i")
    await Timer(HOLD, unit="ns")

    # Sanity: the RAM's init_file preload is readable before any write --
    # confirms the read path independently of the write path under test.
    dut.ce_n.value = 0
    dut.oe_n.value = 0
    _drive_addr(dut, ADDR_PINS_15, 0)
    await Timer(SETTLE, unit="ns")
    got = _read_bus(dut, "dq", suffix="_o")
    assert got == KNOWN_BYTES[0], f"preload sanity: dq_o=0x{got:02x}, want 0x{KNOWN_BYTES[0]:02x}"
    dut.oe_n.value = 1
    await Timer(SETTLE, unit="ns")

    # WRITE_BYTES shares no value with KNOWN_BYTES (the preload) -- a bug
    # that silently no-ops the write and just re-serves the preloaded
    # content would be caught by every single address, not masked by
    # coincidental overlap.
    WRITE_BYTES = [0x90 + i for i in range(16)]
    assert not (set(WRITE_BYTES) & set(KNOWN_BYTES))

    # CE_n gates the WRITE path too, not just the read path -- WE_n low
    # while CE_n is high must NOT commit (matches real async-SRAM
    # behaviour, and proves ce_n isn't read only on the read side of this
    # model). Poison address 5 with a byte that appears nowhere else, with
    # CE_n deasserted throughout the pulse, then confirm it's still the
    # untouched preload value.
    dut.ce_n.value = 1
    _drive_addr(dut, ADDR_PINS_15, 5)
    _drive_bus(dut, "dq", 0xEE, suffix="_i")
    dut.we_n.value = 0
    await Timer(HOLD, unit="ns")
    dut.we_n.value = 1
    await Timer(HOLD, unit="ns")
    _release_bus(dut, "dq", suffix="_i")
    dut.ce_n.value = 0
    dut.oe_n.value = 0
    _drive_addr(dut, ADDR_PINS_15, 5)
    await Timer(SETTLE, unit="ns")
    got = _read_bus(dut, "dq", suffix="_o")
    assert got == KNOWN_BYTES[5], (
        f"CE_n=1 during a WE_n pulse must not write: addr=5 dq_o=0x{got:02x}, "
        f"want unchanged preload 0x{KNOWN_BYTES[5]:02x}"
    )
    dut.oe_n.value = 1
    await Timer(SETTLE, unit="ns")

    # Write, ASCENDING address order (0..15). WE_n is genuinely level-
    # sampled (not edge-triggered) -- held low for a full HOLD period so
    # the 2-flop sync settles well within the pulse, with address/data
    # stable for the whole pulse (matching real async-SRAM write timing).
    for addr in range(16):
        _drive_addr(dut, ADDR_PINS_15, addr)
        _drive_bus(dut, "dq", WRITE_BYTES[addr], suffix="_i")
        dut.we_n.value = 0
        await Timer(HOLD, unit="ns")
        dut.we_n.value = 1
        await Timer(HOLD, unit="ns")
    _release_bus(dut, "dq", suffix="_i")
    dut.ce_n.value = 1
    await Timer(SETTLE, unit="ns")

    # Read back in DESCENDING (reversed/mirrored) address order -- the
    # mirror-witness house rule: reading through the SAME order as
    # written is permutation-blind (e.g. a MAR that never actually
    # latches and just keeps re-writing/re-reading the LAST address would
    # still pass an ascending-write/ascending-read round trip). Each
    # address is checked against the byte written specifically TO IT, not
    # the order it was written in.
    dut.ce_n.value = 0
    dut.oe_n.value = 0
    dut.we_n.value = 1
    for addr in reversed(range(16)):
        _drive_addr(dut, ADDR_PINS_15, addr)
        await Timer(SETTLE, unit="ns")
        got = _read_bus(dut, "dq", suffix="_o")
        assert got == WRITE_BYTES[addr], (
            f"addr={addr} (read in REVERSED order): dq_o=0x{got:02x}, "
            f"want 0x{WRITE_BYTES[addr]:02x} (permutation-blind guard)"
        )
    dut.ce_n.value = 1


@cocotb.test()
async def ram_releases_dq_when_deselected(dut):
    """The RAM's dq_o RELEASE behaviour, asserted directly.

    Companion to test_msi.xcvr_releases_the_side_it_is_not_driving. On the
    real board dq0-7 are ONE bidirectional bus shared with the '245 (U21)
    and, through it, the MDR bus; after the item-1 `inout` -> `_i`/`_o`
    split, `dq_o` carrying 'Z' when the chip is not serving a read is the
    only thing that keeps that shared net single-driver, and it is what
    fpga/synth/bus_resolve.ys's tri-state resolution arbitrates over.
    ram_write_then_read_permuted above only ever samples dq_o while the
    chip IS driving, so a model that drove the bus unconditionally would
    pass it.

    Three deselect conditions, straight off ttl_mcm60256.vhd's own
    `dq0_o <= q(0) when (ce_n = '0' and oe_n = '0') else 'Z'`, plus a
    re-assert of the driven case so none of the Z checks is vacuous. The
    WRITE case matters most: during a write the external driver owns the
    bus, and the RAM must not fight it.

    Self-contained on memory CONTENT: it writes its own witness byte to
    the address it later reads instead of trusting the init_file preload,
    because cocotb runs every @cocotb.test() in this file against ONE
    elaboration and ram_write_then_read_permuted has already overwritten
    addresses 0-15 by the time this runs (found the hard way -- the first
    draft expected KNOWN_BYTES[3]=0x04 and read 0x93)."""
    WITNESS_ADDR, WITNESS = 3, 0x5A

    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    dut.ce_n.value = 1
    dut.oe_n.value = 1
    dut.we_n.value = 1
    _drive_addr(dut, ADDR_PINS_15, WITNESS_ADDR)
    _release_bus(dut, "dq", suffix="_i")
    await Timer(SETTLE, unit="ns")

    def _assert_z(why):
        for i, v in enumerate(_read_bus_str(dut, "dq", suffix="_o")):
            assert v == "Z", f"dq{i}_o: {why} -> {v}, want Z"

    _assert_z("ce_n=1 oe_n=1 (deselected)")

    # Plant the witness byte (ce_n low, we_n pulsed, oe_n high).
    dut.ce_n.value = 0
    _drive_bus(dut, "dq", WITNESS, suffix="_i")
    dut.we_n.value = 0
    await Timer(HOLD, unit="ns")
    dut.we_n.value = 1
    await Timer(HOLD, unit="ns")
    _release_bus(dut, "dq", suffix="_i")
    dut.ce_n.value = 1
    await Timer(SETTLE, unit="ns")

    dut.ce_n.value = 0
    dut.oe_n.value = 1
    await Timer(SETTLE, unit="ns")
    _assert_z("ce_n=0 oe_n=1 (selected, output disabled)")

    dut.ce_n.value = 1
    dut.oe_n.value = 0
    await Timer(SETTLE, unit="ns")
    _assert_z("ce_n=1 oe_n=0 (deselect beats output-enable)")

    # Driving case, so the three checks above cannot pass by the model
    # having simply stopped driving altogether.
    dut.ce_n.value = 0
    dut.oe_n.value = 0
    await Timer(SETTLE, unit="ns")
    got = _read_bus(dut, "dq", suffix="_o")
    assert got == WITNESS, (
        f"ce_n=0 oe_n=0: dq_o=0x{got:02x}, want the witness byte "
        f"0x{WITNESS:02x} written above -- the driven case must still "
        f"drive, or the Z checks above are vacuous")

    # During a WRITE the external driver owns the bus: ce_n low, we_n low,
    # oe_n high. dq_o must be released the whole time.
    dut.oe_n.value = 1
    _drive_bus(dut, "dq", 0x77, suffix="_i")
    dut.we_n.value = 0
    await Timer(HOLD, unit="ns")
    _assert_z("ce_n=0 we_n=0 oe_n=1 (external driver owns the bus)")
    dut.we_n.value = 1
    _release_bus(dut, "dq", suffix="_i")
    dut.ce_n.value = 1
