import os
import sys
from cocotb.clock import Clock
from cocotb.triggers import Timer

import cocotb

# Module testbench (Task 10, copying Task 9's pattern) -- memory.
# Stimulus/assertions touch ONLY fpga/gen/memory.vhd's own contract ports
# (clk_sys, m, n_clk, n_ram_out, n_rom_out, m15_eq_rom_en, n_ram_en,
# write_dir, mdr) -- the same signals tests/dino_bringup/src/mod_memory.c's
# bind() DRIVEs/SAMPLEs on the real rig (this sheet's rig owns the WHOLE
# address bus, per that file's own header). Every test's docstring names
# the mod_memory.c rig test it ports.
#
# Gate equations read straight off fpga/gen/memory.vhd (Task 8's
# generated output, itself netlist-verified against memory.kicad_sch per
# CLAUDE.md):
#   U24 AT28C256 ROM: a0-14 = m(0-14), ce_n = m15_eq_rom_en DIRECTLY (=
#             M15 itself -- selected LOW, so the ROM answers 0x0000-
#             0x7FFF), oe_n = n_rom_out, we_n strapped '1' (write-
#             protected in copper -- read-only, no write path exists).
#   U26 MCM60256AP RAM: a0-14 = m(0-14), ce_n = n_ram_en (a plain INPUT
#             on THIS sheet -- the real ~{RAM_EN}=INV(M15) decode lives
#             on mar.vhd, off this sheet's boundary, so this TB drives
#             n_ram_en directly to emulate it, same as mod_memory.c's own
#             idle_for()), oe_n = n_ram_out, we_n = internal
#             n_ram_write_en.
#   U51 '00   n_write_dir    = INV(write_dir)
#             n_ram_write_en = NAND(write_dir, n_clk)  <- THE WRITE
#             WINDOW. n_clk represents ~{CLK} directly as a port (the
#             real ~CLK net is generated by an inverter elsewhere, off
#             this sheet), so n_clk=1 means CLK is LOW -- this module's
#             REQUIRED minimum half 1 ("RAM write on CLK low only") is
#             this exact gate: WE_n asserted (write enabled) needs BOTH
#             write_dir=1 AND n_clk=1 (CLK low).
#             ram_mdr_dis   = NAND(n_ram_out, n_write_dir)
#             n_ram_mdr_en  = INV(ram_mdr_dis) -- U21's CE, i.e. the RAM
#             buffer opens for a RAM READ or a RAM WRITE, never merely
#             because the address parked on a RAM address (schematic bug
#             2's fix, per CLAUDE.md/mod_memory.c's own header).
#   U19/U21 '245s -- ROM->mdr and RAM<->mdr, both gated as above. m is a
#             plain 'in' port on THIS sheet (not bidirectional -- the real
#             cross-sheet contention lives on mar.vhd/program_counter.vhd,
#             off this boundary), so a plain deposit drives it directly;
#             mdr IS multiply-driven (U19 + U21 both touch it), so it's a
#             Task-13-rework-item-1 split port (`mdr_i`/`mdr_o`, not
#             `inout` -- ghdl-yosys-plugin severs internal nets touching a
#             sub-instance `inout` port at synthesis import): every RAM
#             write below drives `mdr_i` (a true single-driver `in` port,
#             no more Force()/Release() needed) and every readback reads
#             `mdr_o` (this sheet's own drive, 'Z' when neither '245 is
#             enabled).
#
# ROM/RAM reads are now REGISTERED on clk_sys (Task-13 rework item 2, same
# hidden-sampling-clock contract every stateful model already uses) -- one
# clk_sys tick of extra latency, well inside SETTLE's 5-cycle margin below.
#
# ROM content is loaded from fpga/sim/hex/PROG.hex via this sheet's
# u24_init_file generic, overridden by fpga/sim/Makefile
# (MODULE_UNDER_TEST=memory's SIM_ARGS block, since the entity's own
# DEFAULT generic path is relative to fpga/, not fpga/sim/) -- confirmed
# to be the REAL milestone burn (PROG.hex byte 0 = 0x11 = LDAI, not
# 0xA5/the DIAG signature), so this TB imports docs/notes/progrom_gen.py's
# build_real() the same "never retype bytes" way
# test_module_microcode.py imports microcode_gen.build_real().
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "..", "..", "docs", "notes"))
from progrom_gen import build_real as prog_build_real  # noqa: E402
from progrom_gen import SAFE_FILL as PR_SAFE_FILL       # noqa: E402

SETTLE = 50
HOLD = 250

PROG_REAL = prog_build_real()


async def _start(dut):
    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    await Timer(SETTLE, unit="ns")


async def _settle(dut):
    await Timer(SETTLE, unit="ns")


async def _hold(dut):
    await Timer(HOLD, unit="ns")


def _drive_m(dut, addr):
    dut.m.value = addr & 0x7FFF
    dut.m15_eq_rom_en.value = (addr >> 15) & 1


def _idle_for(dut, addr):
    """Ports mod_memory.c's idle_for(): strobes idle, chip selects as the
    MAR board would drive them for this address (ROM_EN = M15 directly,
    ~{RAM_EN} = INV(M15))."""
    dut.n_rom_out.value = 1
    dut.n_ram_out.value = 1
    dut.write_dir.value = 0
    dut.n_clk.value = 0                          # CLK high: write window shut
    dut.n_ram_en.value = 0 if (addr & 0x8000) else 1
    _drive_m(dut, addr)


def _drive_mdr(dut, v):
    dut.mdr_i.value = v & 0xFF


def _release_mdr(dut):
    dut.mdr_i.value = "Z" * 8


async def _bind_idle(dut):
    await _start(dut)
    _idle_for(dut, 0)
    await _settle(dut)


async def _rom_read(dut, addr):
    _idle_for(dut, addr)
    dut.n_rom_out.value = 0
    await _settle(dut)
    v = int(dut.mdr_o.value)
    _idle_for(dut, addr)
    await _settle(dut)
    return v


async def _ram_read(dut, addr):
    _idle_for(dut, addr)
    dut.n_ram_out.value = 0
    await _settle(dut)
    v = int(dut.mdr_o.value)
    _idle_for(dut, addr)
    await _settle(dut)
    return v


async def _ram_write(dut, addr, v):
    """Ports mod_memory.c's ram_write(): rig supplies the byte on mdr,
    write_dir flips U21 to mdr->RAM, then n_clk=1 (CLK low) opens the
    ~{WE} window (U51 gate 2)."""
    _idle_for(dut, addr)
    _drive_mdr(dut, v)
    dut.write_dir.value = 1
    await _settle(dut)                # buffer turns, ~WE still high (n_clk=0)
    dut.n_clk.value = 1               # window OPEN (CLK low)
    await _hold(dut)
    dut.n_clk.value = 0               # window closed, latched
    await _settle(dut)
    _idle_for(dut, addr)
    _release_mdr(dut)
    await _settle(dut)


@cocotb.test()
async def test_memory_ram_write_gated_by_clk_low(dut):
    """Ports mod_memory.c t_memory_window: no_write_when_CLK_high,
    no_write_without_WRITE_DIR, write_lands_in_window -- this module's
    REQUIRED minimum half 1 ('RAM write on CLK low only')."""
    await _bind_idle(dut)
    await _ram_write(dut, 0xA000, 0x11)

    # attempt 1: WRITE_DIR asserted but n_clk stays 0 (CLK HIGH) throughout.
    _idle_for(dut, 0xA000)
    _drive_mdr(dut, 0xEE)
    dut.write_dir.value = 1
    await _settle(dut)                # n_clk never asserted
    _idle_for(dut, 0xA000)
    _release_mdr(dut)
    await _settle(dut)
    got = await _ram_read(dut, 0xA000)
    assert got == 0x11, (
        f"mdr: write_dir=1 with CLK held HIGH (n_clk=0) the whole time -> "
        f"0x{got:02X}, want unchanged 0x11 (no write without CLK low)"
    )

    # attempt 2: n_clk=1 (CLK low) but write_dir stays 0 (idle).
    _idle_for(dut, 0xA000)
    _drive_mdr(dut, 0xEE)
    await _settle(dut)
    dut.n_clk.value = 1               # CLK low, but write_dir never asserted
    await _hold(dut)
    _idle_for(dut, 0xA000)
    _release_mdr(dut)
    await _settle(dut)
    got = await _ram_read(dut, 0xA000)
    assert got == 0x11, (
        f"mdr: n_clk=1 (CLK low) with write_dir never asserted -> "
        f"0x{got:02X}, want unchanged 0x11 (no write without WRITE_DIR)"
    )

    # both together: the window opens and the byte lands.
    await _ram_write(dut, 0xA000, 0x22)
    got = await _ram_read(dut, 0xA000)
    assert got == 0x22, f"mdr: write_dir=1 AND CLK low together -> 0x{got:02X}, want 0x22"


@cocotb.test()
async def test_memory_rom_ram_decode_boundary(dut):
    """Ports mod_memory.c t_memory_select + t_memory_idle: the 0x8000
    boundary is exact (ROM below, RAM at/above), each chip stays off the
    bus in the other's half, and the idle state (no strobe asserted)
    floats mdr in EITHER half -- this module's REQUIRED minimum half 2
    ('ROM/RAM decode'). Retires schematic bug 2 (mdr's U21 CE must not
    open on address alone)."""
    await _bind_idle(dut)
    await _ram_write(dut, 0x8000, 0x5A)
    got_rom = await _rom_read(dut, 0x7FFF)
    assert got_rom == PROG_REAL[0x7FFF], (
        f"mdr: ROM read at 0x7FFF -> 0x{got_rom:02X}, "
        f"want 0x{PROG_REAL[0x7FFF]:02X} (build_real())"
    )
    got_ram = await _ram_read(dut, 0x8000)
    assert got_ram == 0x5A, f"mdr: RAM read at 0x8000 -> 0x{got_ram:02X}, want 0x5A"

    # ROM strobe in the RAM half: ROM deselected (m15_eq_rom_en=1 there),
    # so U19 must not deliver stale/wrong data. In practice this reads
    # all-'Z' (U19's OE is open, but the ROM CHIP ITSELF is deselected so
    # its io pins are 'Z', and U19 dutifully passes that 'Z' through) --
    # compared as a STRING, not int(), since a floating LogicArray can't
    # convert to int; the point either way is "must NOT equal the RAM's
    # own byte".
    _idle_for(dut, 0x8000)
    dut.n_rom_out.value = 0
    await _settle(dut)
    stray_str = str(dut.mdr_o.value)
    _idle_for(dut, 0x8000)
    await _settle(dut)
    want_5a_str = format(0x5A, "08b")
    assert stray_str != want_5a_str, (
        f"mdr: ~{{ROM_OUT}} strobed in the RAM half -> {stray_str}, "
        f"must NOT leak the RAM's 0x5A (ROM chip is deselected there)"
    )

    # idle: neither strobe asserted -- mdr floats, both halves (bug-2
    # retirement: U21's CE must not open on address alone).
    _idle_for(dut, 0xBEEF)
    await _settle(dut)
    mdr_str = str(dut.mdr_o.value)
    assert all(c == "Z" for c in mdr_str), (
        f"mdr: idle, RAM half (0xBEEF) -> {mdr_str}, want all-Z"
    )
    _idle_for(dut, 0x1000)
    await _settle(dut)
    mdr_str = str(dut.mdr_o.value)
    assert all(c == "Z" for c in mdr_str), (
        f"mdr: idle, ROM half (0x1000) -> {mdr_str}, want all-Z"
    )


@cocotb.test()
async def test_memory_rom_content_matches_build_real(dut):
    """Ports mod_memory.c t_memory_romorder's REAL-burn spot-check
    (byte-for-byte against the imported build_real(), never retyped) --
    the first several milestone-program bytes (LDAI 0xFF; OUT; LDAI 0x2F;
    ...) plus a safe-fill address past the program's end."""
    await _bind_idle(dut)
    for addr in range(12):
        got = await _rom_read(dut, addr)
        want = PROG_REAL[addr]
        assert got == want, (
            f"mdr: ROM addr={addr} -> 0x{got:02X}, want 0x{want:02X} (build_real())"
        )
    got = await _rom_read(dut, 0x0100)
    assert got == PR_SAFE_FILL, (
        f"mdr: ROM addr=0x0100 (past the program) -> 0x{got:02X}, "
        f"want 0x{PR_SAFE_FILL:02X} (SAFE_FILL=HALT)"
    )
