import cocotb
from cocotb.clock import Clock
from cocotb.triggers import Timer

# Module testbench (Task 10, copying Task 9's pattern) -- alu. Stimulus/
# assertions touch ONLY fpga/gen/alu.vhd's own contract ports (clk_sys,
# clk, cw11_eq_sa0, cw10_eq_sa1, cw9_eq_sa2, n_alu_out, n_clk,
# n_reg_a_load, n_reg_b_load, n_reset, flag_z, w) -- the same signals
# tests/dino_bringup/src/mod_alu.c's bind() DRIVEs/SAMPLEs on the real
# rig. Every test's docstring names the mod_alu.c rig test it ports.
#
# Gate equations read straight off fpga/gen/alu.vhd (Task 8's generated
# output, itself netlist-verified against alu.kicad_sch per CLAUDE.md):
#   U38/U40 '382  the 8-bit ALU, s0/s1/s2 <= cw11_eq_sa0/cw10_eq_sa1/
#             cw9_eq_sa2 DIRECTLY (plain wire, no gate in between) --
#             this direct port-map wiring IS the "SA field reaches the
#             '382 uninverted" contract this module's minimum requires;
#             per the mod_alu.c comment: S2:S1:S0=SA2:SA1:SA0, code 011 =
#             A+B (ADD), 110 = A&B (AND). CLAUDE.md's own history: the
#             SA field was packed BIT-REVERSED into the microcode ROM
#             image for months (ADD executed as AND) -- that bug lived in
#             docs/notes/microcode_gen.py's ENCODING, not in this sheet's
#             wiring (already netlist-verified correct in Task 8), so
#             this TB proves the WIRING half by driving cw11/cw10/cw9
#             directly and checking the RESULT, independent of whatever
#             microcode_gen.py currently encodes (test_module_microcode.py
#             covers the encoding half separately).
#   U45/U46 '373  TMP_A/TMP_B shadow latches: D = w0-7 (a PLAIN
#             always-driven port, NOT a bus-hold loopback -- unlike
#             registers_a_b.vhd's A/B/C registers, see that file's
#             _load_reg() comment for the race this avoids), LE =
#             internal le_tmp_{a,b} = NOR(n_reg_{a,b}_load, clk).
#   U47 '373  output latch: D = f0-7 (from the '382s, purely
#             combinational), LE = clk directly (transparent while CLK
#             HIGH), OE = n_alu_out.
#   U48 '157  flag mux, S = n_alu_out: passes NEW values only while the
#             ALU drives w; idle it feeds flags back to themselves (hold).
#   U49 '273  flag register: cp = n_clk, so flags commit on the RISING
#             edge of ~CLK = the FALLING edge of CLK. mr_n = n_reset
#             (async clear). Only Q1 (FLAG_Z) is exposed as a port on
#             this sheet (flag_z) -- FLAG_C/V/N are internal, no port
#             (this sheet's only consumer elsewhere is control_word.vhd's
#             flag_z input).
#
# w is a Task-13-rework-item-1 split port (`w_i`/`w_o`, not `inout` --
# ghdl-yosys-plugin severs internal nets touching a sub-instance `inout`
# port at synthesis import): U45/U46 read the sense side (w_i, a PLAIN
# always-driven read, not a bus-hold loopback -- see the header above),
# U47 drives the output side (w_o) when enabled. The TB is w_i's only
# driver, so a plain deposit works -- no more Force()/Release() needed.
SETTLE = 50
HOLD = 250

# op codes = S2:S1:S0 (cw9:cw10:cw11), matching mod_alu.c's ALU_* table.
ALU_CLR, ALU_BSUB, ALU_SUB, ALU_ADD = 0, 1, 2, 3
ALU_XOR, ALU_OR, ALU_AND, ALU_SET = 4, 5, 6, 7


async def _start(dut):
    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    await Timer(SETTLE, unit="ns")


async def _settle(dut):
    await Timer(SETTLE, unit="ns")


async def _hold(dut):
    await Timer(HOLD, unit="ns")


def _clk_set(dut, level):
    # clk AND n_clk are BOTH contract ports (the real ~CLK net is
    # generated by an inverter elsewhere in the machine, off this sheet)
    # -- keep them complementary, same as Task 9's program_counter TB.
    dut.clk.value = level
    dut.n_clk.value = 1 - level


async def _clk_lo(dut):
    _clk_set(dut, 0)
    await _hold(dut)


async def _clk_hi(dut):
    _clk_set(dut, 1)
    await _hold(dut)


def _drive_w(dut, v):
    dut.w_i.value = v & 0xFF


def _release_w(dut):
    dut.w_i.value = "Z" * 8


async def _w_read(dut):
    _release_w(dut)
    await _settle(dut)
    return int(dut.w_o.value)


async def _bind_idle(dut):
    """Mirrors mod_alu.c bind(): both load strobes idle-high, ALU off
    the bus, not in reset, SA=CLR, CLK idle-high."""
    await _start(dut)
    dut.n_reg_a_load.value = 1
    dut.n_reg_b_load.value = 1
    dut.n_alu_out.value = 1
    dut.n_reset.value = 1
    dut.cw11_eq_sa0.value = 0
    dut.cw10_eq_sa1.value = 0
    dut.cw9_eq_sa2.value = 0
    _clk_set(dut, 1)
    await _settle(dut)


def _set_op(dut, op):
    dut.cw11_eq_sa0.value = op & 1
    dut.cw10_eq_sa1.value = (op >> 1) & 1
    dut.cw9_eq_sa2.value = (op >> 2) & 1


async def _load_shadow(dut, load_pin_name, v):
    """Ports mod_alu.c's load_shadow(): U47 off the bus first, w = v,
    strobe the load pin low while CLK is low (LE opens), close, CLK
    high, release w -- safe with THIS closing order (unlike
    registers_a_b.vhd) because w's drive doesn't depend on the strobe
    pin at all; the TB is w's only active driver throughout."""
    pin = getattr(dut, load_pin_name)
    dut.n_alu_out.value = 1
    _drive_w(dut, v)
    await _settle(dut)
    await _clk_lo(dut)
    pin.value = 0
    await _settle(dut)
    pin.value = 1
    await _settle(dut)
    await _clk_hi(dut)
    _release_w(dut)
    await _settle(dut)


async def _compute(dut, op, a, b):
    """Ports mod_alu.c's compute(): load both shadows, set SA, CLK high
    (U47 transparent), n_alu_out low (U47 drives w), read the result.
    Leaves CLK high and n_alu_out low."""
    await _load_shadow(dut, "n_reg_a_load", a)
    await _load_shadow(dut, "n_reg_b_load", b)
    _set_op(dut, op)
    await _clk_hi(dut)
    dut.n_alu_out.value = 0
    await _settle(dut)
    return await _w_read(dut)


async def _commit(dut):
    """Ports mod_alu.c's commit(): falling CLK clocks U49 through n_clk.
    With n_alu_out still low the '157 mux passes the new values."""
    await _clk_lo(dut)
    await _settle(dut)


async def _release_alu(dut):
    dut.n_alu_out.value = 1
    await _clk_hi(dut)
    _release_w(dut)
    await _settle(dut)


@cocotb.test()
async def test_alu_sa_field_uninverted_add_not_and(dut):
    """Ports (the spirit of) hosttest's test_sa_field_reaches_the_382_
    uninverted, against the GENERATED wiring instead of the schematic:
    this module's REQUIRED minimum. cw11_eq_sa0/cw10_eq_sa1/cw9_eq_sa2
    are driven DIRECTLY (bypassing microcode entirely), so a mismatch
    here can only be this sheet's own port-map wiring, never the
    microcode ROM's bit packing (test_module_microcode.py covers that
    layer separately)."""
    await _bind_idle(dut)
    # ADD = S2:S1:S0 = 0:1:1 -> cw9=0, cw10=1, cw11=1.
    got = await _compute(dut, ALU_ADD, 5, 3)
    assert got == 8, (
        f"w: SA(cw9,cw10,cw11)=(0,1,1) a=5 b=3 -> 0x{got:02X}, want 0x08 "
        f"(A+B=8 -- if CW11=SA0 reached S0 INVERTED or swapped with CW9, "
        f"this code would select a different '382 function, not ADD)"
    )
    await _release_alu(dut)
    # AND = S2:S1:S0 = 1:1:0 -> cw9=1, cw10=1, cw11=0 -- the REVERSE of
    # ADD's bit pattern; this is exactly the code ADD would land on if
    # the SA field's bit order were reversed end to end (the historical
    # bug CLAUDE.md documents), so getting AND here AND ADD above proves
    # the two codes are genuinely distinct on this wiring.
    got = await _compute(dut, ALU_AND, 5, 3)
    assert got == 1, (
        f"w: SA(cw9,cw10,cw11)=(1,1,0) a=5 b=3 -> 0x{got:02X}, want 0x01 "
        f"(5 AND 3 = 1)"
    )
    await _release_alu(dut)


@cocotb.test()
async def test_alu_shadow_gated_by_clk_low_and_independent(dut):
    """Ports mod_alu.c t_alu_shadow: TMP_A/TMP_B (via OR passthrough),
    A_and_B_both_held, load_gated_by_CLK_low."""
    await _bind_idle(dut)
    for v in (0x00, 0xFF, 0xC5, 0x3A):
        await _load_shadow(dut, "n_reg_b_load", 0x00)
        got = await _compute(dut, ALU_OR, v, 0x00)
        assert got == v, f"w: TMP_A via OR-with-0 -> 0x{got:02X}, want 0x{v:02X}"
        await _release_alu(dut)

    # independence: loading B must not disturb A.
    await _load_shadow(dut, "n_reg_a_load", 0xAA)
    await _load_shadow(dut, "n_reg_b_load", 0x55)
    _set_op(dut, ALU_OR)
    await _clk_hi(dut)
    dut.n_alu_out.value = 0
    got = await _w_read(dut)
    assert got == 0xFF, f"w: A=0xAA B=0x55 OR -> 0x{got:02X}, want 0xFF (both shadows held)"
    await _release_alu(dut)

    # gating: a strobe with CLK HIGH must not land (U50 stamp).
    await _load_shadow(dut, "n_reg_a_load", 0x3C)
    dut.n_alu_out.value = 1
    _drive_w(dut, 0xC3)
    await _settle(dut)
    await _clk_hi(dut)
    dut.n_reg_a_load.value = 0     # CLK stays high
    await _settle(dut)
    dut.n_reg_a_load.value = 1
    await _settle(dut)
    _release_w(dut)
    await _settle(dut)
    await _load_shadow(dut, "n_reg_b_load", 0x00)
    _set_op(dut, ALU_OR)
    await _clk_hi(dut)
    dut.n_alu_out.value = 0
    got = await _w_read(dut)
    assert got == 0x3C, (
        f"w: strobe with W=0xC3 while CLK stayed HIGH -> 0x{got:02X}, "
        f"want unchanged 0x3C (shadow load must be gated by CLK low)"
    )
    await _release_alu(dut)


@cocotb.test()
async def test_alu_op_vectors(dut):
    """Ports mod_alu.c t_alu_ops (F only -- flag_c/flag_v/flag_n have no
    port on this sheet, see the header note): every one of the 8 SA
    codes across operands that hit carry/borrow/zero edges."""
    await _bind_idle(dut)
    vectors = [
        (ALU_CLR, 0x5A, 0xA5, 0x00),
        (ALU_BSUB, 0x05, 0x03, 0xFE),   # B-A = 3-5 = -2 = 0xFE
        (ALU_SUB, 0x05, 0x03, 0x02),    # A-B = 5-3 = 2
        (ALU_ADD, 0xFF, 0x01, 0x00),    # wraps to zero
        (ALU_XOR, 0xAA, 0x55, 0xFF),
        (ALU_OR, 0xC0, 0x05, 0xC5),
        (ALU_AND, 0xAA, 0x55, 0x00),
        (ALU_SET, 0x00, 0x00, 0xFF),
    ]
    for op, a, b, want in vectors:
        got = await _compute(dut, op, a, b)
        assert got == want, (
            f"w: op={op} a=0x{a:02X} b=0x{b:02X} -> 0x{got:02X}, want 0x{want:02X}"
        )
        await _release_alu(dut)


@cocotb.test()
async def test_alu_flags_commit_and_reset(dut):
    """Ports mod_alu.c t_alu_flags (Z_after_commit, Z_held_over_idle_
    edges, Z_cleared_by_commit) + t_alu_reset (async clear, no clock
    edge needed) -- flag_z is the only flag this sheet exposes as a
    port."""
    await _bind_idle(dut)
    got = await _compute(dut, ALU_SUB, 0x07, 0x07)   # 7-7=0 -> Z should set
    assert got == 0, f"w: SUB 7-7 -> 0x{got:02X}, want 0x00"
    await _commit(dut)
    assert int(dut.flag_z.value) == 1, "flag_z: after committing 7-7=0 -> want 1"
    await _release_alu(dut)

    # idle cycles (n_alu_out stays HIGH): the '157 mux feeds flags back
    # to themselves, so a clock edge with the ALU NOT driving w must not
    # change flag_z even though the shadows/op underneath do.
    await _load_shadow(dut, "n_reg_a_load", 0x01)
    await _load_shadow(dut, "n_reg_b_load", 0x02)
    _set_op(dut, ALU_ADD)
    for _ in range(3):
        await _clk_lo(dut)
        await _clk_hi(dut)
    assert int(dut.flag_z.value) == 1, "flag_z: idle edges (ALU off bus) -> want held at 1"

    # now WITH the ALU enabled: 1+2=3, non-zero -> Z clears on commit.
    got = await _compute(dut, ALU_ADD, 0x01, 0x02)
    assert got == 3, f"w: ADD 1+2 -> 0x{got:02X}, want 0x03"
    assert int(dut.flag_z.value) == 1, "flag_z: before the commit edge -> want still 1"
    await _commit(dut)
    assert int(dut.flag_z.value) == 0, "flag_z: after committing 1+2=3 -> want 0 (cleared)"
    await _release_alu(dut)

    # RESET clears flag_z with no clock edge at all (async mr_n).
    got = await _compute(dut, ALU_SET, 0, 0)         # -> 0xFF, Z=0
    await _commit(dut)
    await _release_alu(dut)
    dut.n_reset.value = 0
    await _settle(dut)
    assert int(dut.flag_z.value) == 0, "flag_z: async RESET asserted -> want 0"
    dut.n_reset.value = 1
    await _settle(dut)
    assert int(dut.flag_z.value) == 0, "flag_z: RESET released -> want still 0 (no spurious set)"
