import cocotb
from cocotb.clock import Clock
from cocotb.triggers import Timer

# Module testbench pattern (Task 9) -- program_counter first, Task 10's
# template for the other eight sheets. Stimulus and assertions touch
# ONLY the sheet's CONTRACT ports -- fpga/gen/program_counter.vhd's own
# port list (clk_sys, clk, n_clk, n_pc_clear, n_pc_load, n_pc_mar_mux,
# cw13_eq_pc_up, reset, m, m15_eq_rom_en) -- the exact same signals the
# bench rig DRIVEs/SAMPLEs per tests/dino_bringup/src/mod_pc.c's own
# bind(): same doctrine ("sample a signal at block level only if ...";
# here, the whole module IS the block, so every contract port is fair
# game), new instrument. Every test's docstring names the rig test(s) in
# mod_pc.c it ports, and every assertion message names the failing
# signal plus the T-by-T values that produced it, per CLAUDE.md's "NO
# BLIND COUNTERS" rule.
#
# Gate equations below are read straight off fpga/gen/program_counter.vhd
# (netlist-verified in Task 8, not re-derived from memory here) and match
# mod_pc.c's own header comment and CLAUDE.md's machine invariant:
#   U10 '02:  pc_clear_or_reset = OR(NOR(~PC_CLEAR, CLK), RESET)
#             -> PC_CLEAR lands ONLY while CLK is LOW; RESET is un-gated.
#   U36 '00:  pc_up_stable       = NAND(PC_UP, ~CLK)  -> counts on CLK's
#             RISING edge (while PC_UP is held asserted through it).
#             n_pc_load_stable   = NAND(NOT(~PC_LOAD), ~CLK) -> transparent
#             (follows ~PC_LOAD live) ONLY while CLK is LOW, pinned
#             deasserted while CLK is HIGH -- PC_LOAD lands ONLY at CLK low.
#   U11/U12 '245 (dir='1', ce_n=~PC_LOAD):      m -> pcd  (bus into PC's
#             parallel-load inputs)
#   U13/U14 '245 (dir='0', ce_n=~PC_MAR_MUX):   pc -> m   (PC drives the
#             M bus; m15_eq_rom_en carries PC bit 15, the composite net
#             Task 8 discovered is dual-labeled ROM_EN elsewhere)
#
# Timing discipline (Task 5's test_stateful.py; CLAUDE.md "clk_sys=100MHz,
# machine CLK 500ns+ in TBs"): clk_sys is 100MHz (10ns period) and the
# '193/'245 models sample against it through a hidden 2-flop sync, so
# every stimulus change is followed by SETTLE (50ns, 5 clk_sys cycles,
# comfortably >=3) before any assertion, and the machine CLK pin is held
# at each level for HOLD (250ns) -- a realistic ~500ns-period machine
# clock, not a race against the synchronizer.
SETTLE = 50   # ns -- >3 clk_sys cycles
HOLD = 250    # ns -- half-period of a slow, machine-realistic CLK
M_WIDTH = 15  # m(14 downto 0); bit 15 lives on the m15_eq_rom_en port


# --- low-level contract-port helpers (the pattern Task 10 copies) --------

async def _start(dut):
    cocotb.start_soon(Clock(dut.clk_sys, 10, unit="ns").start())
    await Timer(SETTLE, unit="ns")


async def _settle(dut):
    await Timer(SETTLE, unit="ns")


async def _hold(dut):
    await Timer(HOLD, unit="ns")


def _clk_set(dut, level):
    # clk AND n_clk are BOTH contract inputs (mod_pc.c's clk_bind() binds
    # and drives both pins directly -- the real ~CLK net is generated by
    # an inverter elsewhere in the machine, off this sheet). Keep them
    # complementary, exactly like the rig does.
    dut.clk.value = level
    dut.n_clk.value = 1 - level


async def _clk_hi(dut):
    _clk_set(dut, 1)
    await _hold(dut)


async def _clk_lo(dut):
    _clk_set(dut, 0)
    await _hold(dut)


async def _step(dut):
    # One full machine-CLK pulse, low then high -- counts fire on the
    # RISING edge (mod_pc.c count_n(): "lo -> hi: count on the rise").
    await _clk_lo(dut)
    await _clk_hi(dut)


async def _reset_pulse(dut):
    dut.reset.value = 1
    await _settle(dut)
    dut.reset.value = 0
    await _settle(dut)


def _release_m(dut):
    # mod_pc.c's bus_m_release(): the rig (here, the TB) stops driving M
    # so the DUT's own '245 drivers (or nothing, if disabled) are the
    # only source -- release BEFORE the DUT is expected to drive, or a
    # stale TB poke fights the real driver (fpga/spike/test_spike_xcvr.py's
    # documented hazard).
    #
    # m_i/m15_eq_rom_en_i (Task-13 rework item 1: `m`/`m15_eq_rom_en`
    # split from `inout` into `_i`/`_o` pairs -- ghdl-yosys-plugin severs
    # internal nets touching a sub-instance `inout` port at synthesis
    # import) are true single-driver `in` ports -- the TB is their only
    # driver, so a plain deposit is safe and persists exactly as written;
    # no more Force()/Release() needed (that was only ever required
    # because the old single `inout` port was ALSO driven by this sheet's
    # own U13/U14).
    dut.m_i.value = "Z" * M_WIDTH
    dut.m15_eq_rom_en_i.value = "Z"


def _drive_m(dut, v16):
    dut.m_i.value = v16 & ((1 << M_WIDTH) - 1)
    dut.m15_eq_rom_en_i.value = (v16 >> M_WIDTH) & 1


def _read_m(dut):
    # m_o/m15_eq_rom_en_o is this sheet's OWN drive -- 'Z' when U13/U14
    # are disabled, exactly the observable the old single inout net gave
    # when nothing local was driving it.
    lo = int(dut.m_o.value)
    hi = int(dut.m15_eq_rom_en_o.value)
    return lo | (hi << M_WIDTH)


async def _pc_read(dut):
    await _settle(dut)
    return _read_m(dut)


async def _load16(dut, v):
    # Ports mod_pc.c's load16(): mux PC off M BEFORE the TB drives it (or
    # U13/U14 fight the TB's drive through their series resistors -- the
    # same "release-then-drive" discipline the inout m port needs), strobe
    # ~PC_LOAD while CLK is LOW (the only phase ~PC_LOAD_STABLE can
    # assert), then restore mux and release M back to the DUT.
    dut.n_pc_mar_mux.value = 1
    await _settle(dut)
    _drive_m(dut, v)
    await _settle(dut)
    await _clk_lo(dut)
    dut.n_pc_load.value = 0
    await _settle(dut)
    dut.n_pc_load.value = 1
    await _settle(dut)
    await _clk_hi(dut)
    _release_m(dut)
    await _settle(dut)
    dut.n_pc_mar_mux.value = 0
    await _settle(dut)


async def _count_n(dut, n):
    # Ports mod_pc.c's count_n(): PC_UP toggled only while CLK is HIGH
    # (deasserting during CLK-low would fire a spurious UP edge -- same
    # rule the real machine's control-word timing gives).
    dut.cw13_eq_pc_up.value = 1
    await _settle(dut)
    for _ in range(n):
        await _step(dut)
    dut.cw13_eq_pc_up.value = 0
    await _settle(dut)


async def _bind_idle(dut):
    """Reproduce mod_pc.c bind()'s idle state on the contract ports.

    Deliberately does NOT call _release_m()/_drive_m() here: the mux
    starts (and stays, across every test that never calls _load16)
    enabled, so the DUT's own U13/U14 already drive `m`/`m15_eq_rom_en`
    from VHDL's t=0 initialization -- the TB was never driving this
    inout port in the first place, so there is nothing to force or
    release. Touching it anyway (an earlier version of this helper called
    a plain, non-Force/Release value write here "just to be safe") is
    exactly the bug that motivated _drive_m()/_release_m()'s Force()/
    Release() pairing: caught empirically, a plain write left `m` bits
    that hadn't yet changed value stuck at the written value indefinitely,
    surviving many further clk_sys ticks and PC counts. Only touch this
    inout port through _drive_m()/_release_m(), and only when the TB
    genuinely needs to inject a value.
    """
    await _start(dut)
    dut.n_pc_clear.value = 1     # clear idle
    dut.n_pc_load.value = 1      # load idle
    dut.cw13_eq_pc_up.value = 0  # count disabled
    dut.reset.value = 0
    dut.n_pc_mar_mux.value = 0   # PC drives M -- tests read it directly
    _clk_set(dut, 1)             # idle HIGH: PC_UP/clear-safe phase
    await _settle(dut)


# --- tests -----------------------------------------------------------------

@cocotb.test()
async def test_reset_clears_and_counts_on_clk_rise(dut):
    """Ports mod_pc.c t_pc_presence: PC_zero_after_reset, PC_counts."""
    await _bind_idle(dut)
    await _reset_pulse(dut)
    got = await _pc_read(dut)
    assert got == 0, f"m/m15_eq_rom_en: after RESET pulse -> 0x{got:04X}, want 0x0000"

    await _count_n(dut, 1)
    got = await _pc_read(dut)
    assert got == 1, f"m/m15_eq_rom_en: after RESET + 1 count -> 0x{got:04X}, want 0x0001"


@cocotb.test()
async def test_pc_holds_when_pc_up_deasserted(dut):
    """Ports mod_pc.c t_pc_count: PC_increments_each_step (asserted after
    EVERY single CLK pulse across all 16 steps, matching the rig's
    per-step granularity -- mod_pc.c:172-177's loop checks pc_read()==i
    at each of the 16 steps, not just a final tally after several batched
    steps; a mid-sequence miscount that happens to net out correct after
    N steps would pass a batched check but fail this one, same as the
    rig), PC_holds_UP_low."""
    await _bind_idle(dut)
    await _reset_pulse(dut)

    dut.cw13_eq_pc_up.value = 1
    await _settle(dut)
    for i in range(1, 17):
        await _step(dut)
        got = await _pc_read(dut)
        assert got == i, (
            f"m: CLK pulse {i} of 16 with PC_UP=1 -> 0x{got:04X}, "
            f"want 0x{i:04X} (PC must increment on EVERY single step, "
            f"not just net out correctly after several)"
        )
    dut.cw13_eq_pc_up.value = 0
    await _settle(dut)

    # PC_UP now deasserted; pulse CLK 8 more times -- PC must not creep.
    for i in range(8):
        await _step(dut)
        got = await _pc_read(dut)
        assert got == 16, (
            f"m: CLK pulse #{i + 1} of 8 with PC_UP=0 -> 0x{got:04X}, "
            f"want held at 0x0010 (count must not fire without PC_UP)"
        )


@cocotb.test()
async def test_pc_count_edge_is_clk_rise_not_fall(dut):
    """Ports mod_pc.c t_pc_phase: no_count_UP_toggle_CLK_high, no_count_on_CLK_fall, count_on_CLK_rise."""
    await _bind_idle(dut)
    await _load16(dut, 0x0100)

    # Toggling PC_UP while CLK stays HIGH must never fire a count: the
    # '193's UP pin is NAND(PC_UP, ~CLK); with CLK high (~CLK low) that
    # pin is pinned HIGH regardless of PC_UP, so no edge ever appears.
    for i in range(4):
        dut.cw13_eq_pc_up.value = 1
        await _settle(dut)
        dut.cw13_eq_pc_up.value = 0
        await _settle(dut)
    got = await _pc_read(dut)
    assert got == 0x0100, (
        f"m: PC_UP toggled 4 times at CLK-high -> 0x{got:04X}, want "
        f"unchanged 0x0100 (UP pin is pinned by ~CLK, not PC_UP, while CLK is high)"
    )

    dut.cw13_eq_pc_up.value = 1
    await _settle(dut)
    await _clk_lo(dut)
    got = await _pc_read(dut)
    assert got == 0x0100, (
        f"m: CLK fell with PC_UP held asserted -> 0x{got:04X}, want "
        f"unchanged 0x0100 (falling edge must not count)"
    )
    await _clk_hi(dut)
    got = await _pc_read(dut)
    assert got == 0x0101, (
        f"m: CLK rose with PC_UP held asserted -> 0x{got:04X}, want "
        f"0x0101 (rising edge counts)"
    )
    dut.cw13_eq_pc_up.value = 0
    await _settle(dut)


@cocotb.test()
async def test_rollover_carry_between_193_stages(dut):
    """Ports mod_pc.c t_pc_carry: carry_chain, ROM_EN_low_below, ROM_EN_high_at_0x8000."""
    await _bind_idle(dut)
    boundaries = [(0x00FF, 0x0100), (0x0FFF, 0x1000), (0x7FFF, 0x8000), (0xFFFF, 0x0000)]
    for frm, to in boundaries:
        await _load16(dut, frm)
        await _count_n(dut, 1)
        got = await _pc_read(dut)
        assert got == to, (
            f"m: loaded 0x{frm:04X} + 1 count -> 0x{got:04X}, want 0x{to:04X} "
            f"(carry must ripple across the '193 cascade boundary)"
        )

    # m15_eq_rom_en doubles as PC bit 15 AND, elsewhere in the real
    # machine, the dual-labeled ROM_EN net (Task 8's composite-alias
    # discovery) -- flips exactly at the 0x8000 boundary.
    await _load16(dut, 0x7FFF)
    got = await _pc_read(dut)
    assert (got & 0x8000) == 0, (
        f"m15_eq_rom_en: PC=0x{got:04X} (loaded 0x7FFF) -> bit15 set, "
        f"want 0 (ROM_EN low below 0x8000)"
    )
    await _count_n(dut, 1)
    got = await _pc_read(dut)
    assert (got & 0x8000) != 0, (
        f"m15_eq_rom_en: PC=0x{got:04X} (0x7FFF + 1) -> bit15 clear, "
        f"want 1 (ROM_EN high at 0x8000)"
    )


@cocotb.test()
async def test_pc_load_patterns_and_walking_bits(dut):
    """Ports mod_pc.c t_pc_load's first two blocks: load_pattern, load_walk1, load_walk0."""
    await _bind_idle(dut)
    for pat in (0x0000, 0xFFFF, 0xAAAA, 0x5555):
        await _load16(dut, pat)
        got = await _pc_read(dut)
        assert got == pat, f"m: loaded 0x{pat:04X} -> read back 0x{got:04X}"

    for i in range(16):
        v1 = 1 << i
        await _load16(dut, v1)
        got = await _pc_read(dut)
        assert got == v1, f"m: load_walk1 bit{i} -> loaded 0x{v1:04X}, read 0x{got:04X}"

        v0 = (~v1) & 0xFFFF
        await _load16(dut, v0)
        got = await _pc_read(dut)
        assert got == v0, f"m: load_walk0 bit{i} -> loaded 0x{v0:04X}, read 0x{got:04X}"


@cocotb.test()
async def test_pc_load_gated_by_clk_low(dut):
    """Ports mod_pc.c t_pc_load's gating block: load_gated_by_CLK_low."""
    await _bind_idle(dut)
    await _load16(dut, 0x1234)

    # ~PC_LOAD strobed while CLK stays HIGH must not land (U36's third
    # gate: n_pc_load_stable only tracks ~PC_LOAD while CLK is low).
    dut.n_pc_mar_mux.value = 1
    await _settle(dut)
    _drive_m(dut, 0x4321)
    await _settle(dut)
    dut.n_pc_load.value = 0
    await _settle(dut)
    dut.n_pc_load.value = 1
    await _settle(dut)
    _release_m(dut)
    await _settle(dut)
    dut.n_pc_mar_mux.value = 0
    await _settle(dut)

    got = await _pc_read(dut)
    assert got == 0x1234, (
        f"m: ~PC_LOAD strobed with M=0x4321 while CLK stayed HIGH -> "
        f"0x{got:04X}, want unchanged 0x1234 (load must be gated by CLK low)"
    )


@cocotb.test()
async def test_pc_clear_gated_by_clk_low_reset_ungated(dut):
    """Ports mod_pc.c t_pc_clear: clear_blocked_CLK_high, clear_lands_CLK_low, RESET_clears_CLK_high, RESET_clears_CLK_low."""
    await _bind_idle(dut)

    await _load16(dut, 0x0BAD)
    dut.n_pc_clear.value = 0
    await _settle(dut)  # CLK stays idle-high
    got = await _pc_read(dut)
    assert got == 0x0BAD, (
        f"m: ~PC_CLEAR asserted at CLK-high -> 0x{got:04X}, want "
        f"unchanged 0x0BAD (U10's NOR gate blocks clear while CLK is high)"
    )
    await _clk_lo(dut)
    got = await _pc_read(dut)
    assert got == 0x0000, (
        f"m: ~PC_CLEAR held into CLK-low -> 0x{got:04X}, want 0x0000 "
        f"(clear lands once CLK goes low)"
    )
    dut.n_pc_clear.value = 1
    await _settle(dut)
    await _clk_hi(dut)

    await _load16(dut, 0x00AA)
    await _reset_pulse(dut)  # CLK stays HIGH throughout
    got = await _pc_read(dut)
    assert got == 0x0000, (
        f"m: RESET pulsed at CLK-high -> 0x{got:04X}, want 0x0000 "
        f"(RESET leg is not CLK-gated, unlike ~PC_CLEAR)"
    )

    await _load16(dut, 0x0055)
    await _clk_lo(dut)
    await _reset_pulse(dut)
    got = await _pc_read(dut)
    assert got == 0x0000, f"m: RESET pulsed at CLK-low -> 0x{got:04X}, want 0x0000"
    await _clk_hi(dut)


@cocotb.test()
async def test_pc_mux_floats_m_when_disabled(dut):
    """Ports mod_pc.c t_pc_mux: PC_drives_M_mux_low, floats, PC_redrives_M_mux_low."""
    await _bind_idle(dut)
    await _load16(dut, 0x5A5A)
    got = await _pc_read(dut)
    assert got == 0x5A5A, f"m: PC after load -> 0x{got:04X}, want 0x5A5A"

    dut.n_pc_mar_mux.value = 1
    await _settle(dut)
    m_str = str(dut.m_o.value)
    assert all(c == "Z" for c in m_str), (
        f"m_o: ~PC_MAR_MUX disabled -> {m_str}, want all-Z (U13/U14 tri-stated, "
        f"nothing else drives m while ~PC_LOAD is also idle)"
    )
    m15_str = str(dut.m15_eq_rom_en_o.value)
    assert m15_str == "Z", f"m15_eq_rom_en_o: ~PC_MAR_MUX disabled -> {m15_str}, want Z"

    dut.n_pc_mar_mux.value = 0
    await _settle(dut)
    got = await _pc_read(dut)
    assert got == 0x5A5A, f"m: ~PC_MAR_MUX re-enabled -> 0x{got:04X}, want 0x5A5A (PC redrives M)"


@cocotb.test()
async def test_pc_precedence(dut):
    """Ports mod_pc.c t_pc_precedence: clear_beats_load, load_after_clear_release, RESET_beats_count, count_from_reset, count_from_loaded."""
    await _bind_idle(dut)

    # Clear + load both asserted at CLK-low, load released first: the
    # '193's async CLR pin dominates ~LOAD_n (checked first in the model's
    # priority chain).
    await _load16(dut, 0x0777)
    dut.n_pc_mar_mux.value = 1
    await _settle(dut)
    _drive_m(dut, 0xAAAA)
    await _settle(dut)
    await _clk_lo(dut)
    dut.n_pc_load.value = 0
    dut.n_pc_clear.value = 0
    await _settle(dut)
    dut.n_pc_load.value = 1
    await _settle(dut)  # load off first, clear still holds
    dut.n_pc_clear.value = 1
    await _settle(dut)
    await _clk_hi(dut)
    _release_m(dut)
    await _settle(dut)
    dut.n_pc_mar_mux.value = 0
    await _settle(dut)
    got = await _pc_read(dut)
    assert got == 0x0000, (
        f"m: clear+load both asserted, load released first -> 0x{got:04X}, "
        f"want 0x0000 (clear beats load)"
    )

    # Same setup, release order flipped: clear off first, load (still
    # asserted) lands.
    dut.n_pc_mar_mux.value = 1
    await _settle(dut)
    _drive_m(dut, 0xAAAA)
    await _settle(dut)
    await _clk_lo(dut)
    dut.n_pc_load.value = 0
    dut.n_pc_clear.value = 0
    await _settle(dut)
    dut.n_pc_clear.value = 1
    await _settle(dut)  # clear off first, load wins now
    dut.n_pc_load.value = 1
    await _settle(dut)
    await _clk_hi(dut)
    _release_m(dut)
    await _settle(dut)
    dut.n_pc_mar_mux.value = 0
    await _settle(dut)
    got = await _pc_read(dut)
    assert got == 0xAAAA, (
        f"m: clear released before load -> 0x{got:04X}, want 0xAAAA "
        f"(load lands once clear is released first)"
    )

    # RESET mid-count, then counting resumes from zero.
    await _count_n(dut, 3)
    await _reset_pulse(dut)
    got = await _pc_read(dut)
    assert got == 0x0000, f"m: RESET mid-count -> 0x{got:04X}, want 0x0000 (RESET beats count)"
    await _count_n(dut, 2)
    got = await _pc_read(dut)
    assert got == 0x0002, f"m: 2 counts after RESET -> 0x{got:04X}, want 0x0002"

    # Count continues from a loaded value (the JMP-then-fetch seam).
    await _load16(dut, 0x1234)
    await _count_n(dut, 2)
    got = await _pc_read(dut)
    assert got == 0x1236, f"m: loaded 0x1234 + 2 counts -> 0x{got:04X}, want 0x1236"
