/* GENERATED by docs/notes/progrom_gen.py — do not edit.
   Regenerate: python3 docs/notes/progrom_gen.py */
#ifndef PROGROM_EXPECT_H
#define PROGROM_EXPECT_H
#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif
#include <stdint.h>

#define PR_SIZE 32768u
#define PR_SAFE_FILL 0xFFu

/* burn signatures: byte 0 of each image */
#define PR_DIAG_BYTE0 0xA5u
#define PR_REAL_BYTE0 0x11u

/* CRC-16/CCITT-FALSE over all 32768 bytes */
#define PR_CRC_REAL 0x8577u
#define PR_CRC_DIAG 0xDFE7u

#define PR_DIAG_ZERO 0xA5u
#define PR_DIAG_WALK 0x40u

/* diag value is a pure function of its address — the rig computes
   it rather than carrying a 32KB table. Self-naming on 0 and 2^k. */
static inline uint8_t pr_diag_byte(uint16_t a) {
    a &= (uint16_t)(PR_SIZE - 1u);
    if (a == 0u) return PR_DIAG_ZERO;
    if ((a & (uint16_t)(a - 1u)) == 0u) {
        uint8_t k = 0;
        while ((uint16_t)(a >> k) > 1u) k++;
        return (uint8_t)(PR_DIAG_WALK | k);
    }
    return (uint8_t)(((uint16_t)(a * 0x9Du)) ^ (a >> 5));
}

/* the shipped program; every address at or past PR_PROGRAM_LEN
   reads PR_SAFE_FILL */
#define PR_PROGRAM_LEN 10u
static const uint8_t PR_PROGRAM[PR_PROGRAM_LEN] PROGMEM = {
    0x11, 0xFF, 0x51, 0x11, 0x2F, 0x12, 0x1E, 0x41, 0x51, 0xFF,
};

#define PR_EXPECT_SUM 0x4Du   /* the milestone result */
#define PR_POISON 0xFFu   /* OB is set to this BEFORE the sum is computed */
#define PR_EXPECT_ENDS 6u   /* one END per instruction retired */

#endif


/* Worst-case ambiguity of three CONSECUTIVE diag bytes: the most
   addresses that can share one triple. block2.fetch matches such a
   triple to prove the fetch reads ROM at PC, PC+1, PC+2, so a match
   count at or below this is meaningful and anything above it is not.
   STRUCTURAL, not luck — generated, never hand-picked. */
#define PR_DIAG_TRIPLE_MAX 8u

/* progressive ISA-coverage images. Each ends OUT; HALT
   because OB is the only datapath observable on the block
   ladder. Burn as needed; PROG.bin (the milestone) is never
   regenerated under another name. */
#define PR_COV_COUNT 29u
typedef struct { const char *name; uint16_t crc;
                 uint8_t expect_ob; uint8_t expect_ends;
                 uint8_t sw; uint8_t needs_sw; } prcov_t;
static const prcov_t PR_COVERAGE[PR_COV_COUNT] = {
    {"probe", 0x254Eu, 0x39u, 2u, 0x00u, 0u},
    {"adda", 0xAC3Du, 0x39u, 4u, 0x00u, 0u},
    {"addb", 0x8DAEu, 0x39u, 4u, 0x00u, 0u},
    {"dip", 0xFEE3u, 0x4Du, 6u, 0x1Eu, 1u},
    {"alu", 0x642Au, 0x39u, 13u, 0x00u, 0u},
    {"mem", 0x3E4Bu, 0xC5u, 5u, 0x00u, 0u},
    {"flow", 0xCED0u, 0x39u, 7u, 0x00u, 0u},
    {"loop", 0x8727u, 0x15u, 33u, 0x00u, 0u},
    {"mardisc", 0x2066u, 0x6Bu, 8u, 0x00u, 0u},
    {"pads", 0x749Au, 0x40u, 5u, 0x00u, 0u},
    {"sp1", 0x5F58u, 0x2Cu, 5u, 0x00u, 0u},
    {"sp2", 0xFBA3u, 0x53u, 9u, 0x00u, 0u},
    {"sp3", 0x76FFu, 0x2Cu, 9u, 0x00u, 0u},
    {"sp", 0xC047u, 0x27u, 9u, 0x00u, 0u},
    {"calladdr", 0x7D79u, 0x5Cu, 15u, 0x00u, 0u},
    {"callraw", 0xD709u, 0x2Au, 7u, 0x00u, 0u},
    {"call", 0x14C9u, 0x4Bu, 8u, 0x00u, 0u},
    {"stack", 0x1A77u, 0x27u, 13u, 0x00u, 0u},
    {"ramexec", 0x9BC7u, 0x6Eu, 21u, 0x00u, 0u},
    {"jnc", 0x64C0u, 0x6Cu, 8u, 0x00u, 0u},
    {"jncswap", 0x3841u, 0xEEu, 8u, 0x00u, 0u},
    {"mov", 0x234Bu, 0x9Cu, 6u, 0x00u, 0u},
    {"ptr", 0x8F67u, 0x22u, 21u, 0x00u, 0u},
    {"shl", 0x0E11u, 0xA4u, 9u, 0x00u, 0u},
    {"ind", 0x9B7Eu, 0x63u, 10u, 0x00u, 0u},
    {"indst", 0xAB5Bu, 0x5Bu, 9u, 0x00u, 0u},
    {"indj", 0x81A8u, 0x6Cu, 7u, 0x00u, 0u},
    {"serid", 0xEE88u, 0x55u, 6u, 0x00u, 0u},
    {"serid_aa", 0x74B4u, 0xAAu, 6u, 0x00u, 0u},
};